console.log(`NODE_ENV ${process.env.NODE_ENV}`)
console.log(`SOME_TEST_ENV ${process.env.SOME_TEST_ENV}`)
console.log(`SOME_DEV_ENV ${process.env.SOME_DEV_ENV}`)
console.log(`LOG_LEVEL ${process.env.LOG_LEVEL}`)
console.log(`LOG_ENABLED ${process.env.LOG_ENABLED}`)